/**
 * Deterministic renderer for docs/demo/SHOWCASE.md.
 *
 * A scenario records ordered interaction {@link Event}s as it runs; this module
 * turns them into a Mermaid sequenceDiagram plus a before/after balance table.
 * Output is a pure function of the recorded events — no timestamps, wall-clock,
 * or random ids — so two runs of a correct system produce byte-identical files
 * (the `demo:check` freshness gate depends on this).
 */

export type Theme = 'Lifecycle' | 'Resilience' | 'Consistency';

export type Participant = 'Employee' | 'Manager' | 'Admin' | 'Service' | 'HCM' | 'DB';

export interface Event {
  readonly from: Participant;
  readonly to: Participant;
  /** Arrow label, e.g. `POST /requests` or `adjust -2 (verified)`. */
  readonly label: string;
  /** Rendered as a dashed reply arrow when true. */
  readonly reply?: boolean;
  /** Rendered as a `Note over <from>` instead of an arrow. */
  readonly note?: boolean;
}

export interface BalanceSnapshot {
  readonly total: number;
  readonly reserved: number;
  readonly available: number;
}

export interface ScenarioRecord {
  readonly id: string;
  readonly title: string;
  readonly theme: Theme;
  /** Brief challenge tag(s) from the take-home, e.g. ['Challenge 2', 'Challenge 4']. */
  readonly challenges: string[];
  readonly intro: string;
  readonly events: Event[];
  readonly before?: BalanceSnapshot;
  readonly after?: BalanceSnapshot;
  /** One-line takeaways printed under the diagram. */
  readonly takeaways: string[];
}

const PARTICIPANT_ORDER: Participant[] = ['Employee', 'Manager', 'Admin', 'Service', 'HCM', 'DB'];

function usedParticipants(events: Event[]): Participant[] {
  const seen = new Set<Participant>();
  for (const e of events) {
    seen.add(e.from);
    seen.add(e.to);
  }
  return PARTICIPANT_ORDER.filter((p) => seen.has(p));
}

function alias(p: Participant): string {
  return p === 'HCM' ? 'HCM as HCM (mock)' : `${p} as ${p}`;
}

function renderDiagram(events: Event[]): string {
  const lines = ['```mermaid', 'sequenceDiagram'];
  for (const p of usedParticipants(events)) lines.push(`    participant ${alias(p)}`);
  for (const e of events) {
    if (e.note) {
      lines.push(`    Note over ${e.from}: ${e.label}`);
    } else {
      const arrow = e.reply ? '-->>' : '->>';
      lines.push(`    ${e.from}${arrow}${e.to}: ${e.label}`);
    }
  }
  lines.push('```');
  return lines.join('\n');
}

function renderBalanceTable(before?: BalanceSnapshot, after?: BalanceSnapshot): string {
  if (!before || !after) return '';
  return [
    '',
    '| Balance | total | reserved | available |',
    '|---|---|---|---|',
    `| before | ${before.total} | ${before.reserved} | ${before.available} |`,
    `| after | ${after.total} | ${after.reserved} | ${after.available} |`,
  ].join('\n');
}

function renderScenario(s: ScenarioRecord, index: number): string {
  const badges = s.challenges.length ? ` — \`${s.challenges.join(' · ')}\`` : '';
  const parts = [
    `### ${index}. ${s.title}${badges}`,
    '',
    `_${s.theme}._ ${s.intro}`,
    '',
    renderDiagram(s.events),
    renderBalanceTable(s.before, s.after),
    '',
    ...s.takeaways.map((t) => `- ${t}`),
  ];
  return parts.join('\n');
}

const HEADER = `# System-Design Showcase

> **Generated by \`npm run demo:scenarios\`.** Do not edit by hand — it is regenerated from a live run of the service + mock HCM, and \`npm run demo:check\` fails CI if this file drifts from real behavior. Each section's sequence diagram is built from the actual calls made during the run.

This walkthrough boots the real time-off service and a mock HCM as separate processes, drives them over HTTP, and asserts every outcome. It centers the take-home's four challenges and ranges wider to show the system's design: the reservation model, both saga directions, HCM resilience, and consistency under concurrency and external change.

The four challenges from the brief:

1. **External writers** refresh HCM balances out-of-band (anniversary / year-start) → reconciliation.
2. **Realtime HCM API** for getting/sending single values → the saga's adjust call.
3. **Batch HCM endpoint** for the whole corpus → batch reconciliation.
4. **Unreliable HCM errors** — defended via the arithmetic check, circuit breaker, and stuck-state sweep.

See \`docs/TRD.md\` for the design narrative and \`docs/trd/traceability.md\` for the requirement→test map.
`;

function renderIndex(records: ScenarioRecord[]): string {
  const themes: Theme[] = ['Lifecycle', 'Resilience', 'Consistency'];
  const lines = ['## Scenarios', ''];
  let n = 0;
  for (const theme of themes) {
    lines.push(`**${theme}**`, '');
    for (const s of records) {
      if (s.theme !== theme) continue;
      n += 1;
      const tag = s.challenges.length ? ` (${s.challenges.join(', ')})` : '';
      lines.push(`${n}. ${s.title}${tag}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/** Renders the full SHOWCASE.md. Deterministic in `records`. */
export function renderShowcase(records: ScenarioRecord[]): string {
  const ordered = orderByTheme(records);
  const sections = ordered.map((s, i) => renderScenario(s, i + 1));
  return [HEADER, renderIndex(ordered), '---', '', sections.join('\n\n---\n\n'), ''].join('\n');
}

function orderByTheme(records: ScenarioRecord[]): ScenarioRecord[] {
  const themes: Theme[] = ['Lifecycle', 'Resilience', 'Consistency'];
  return [...records].sort((a, b) => themes.indexOf(a.theme) - themes.indexOf(b.theme));
}
